### PR TITLE
Math Magicians: tests

### PR DESCRIPTION
**Pull request by Dangelo-JAN**
# In this milestone we:

Created all the test and the snapshots for the Calculator app.

### CODE REVIEW

**Comment by Dangelo-JAN** [comment]
Note: I made a mistake with the previous pull request sent (ending with 6) and had to merge it. Therefore i had to create another pull request for submission. Initially I thought that test  was just for logic not realizing it was for the all the app, and so, I had to create  another branch named  "feature-without-test" from the "feature branch" (that was the branch to our previous pull request).

I'm sorry for the confusion.
I hope that you kindly can understand the situation and accept this new pull request. 

We will appreciate that.

**Review by mahbubul14 — CHANGES_REQUESTED** [review]
Hi @Dangelo-JAN & @AminaBuhari  ,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

# Required Changes ♻️

- [x] Please add `npm test` instead of `npm run` in this section on the README file so a user is informed how to run tests.
r1

###  To Highlights
:heavy_check_mark: No linters error.
:heavy_check_mark: Github flow used properly.
:heavy_check_mark: Well implemented test.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also reach me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by Dangelo-JAN** [comment]
Changes Done in the README.md file of the feature-with-test branch

**Review by Cathella — APPROVED** [review]
## 🔥 Status: Approved 🟢

### Hi @Dangelo-JAN👋🏻, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
